- name: install python
  hosts: all
  user: root
  gather_facts: no
  tasks:
  - raw: apt-get update -qq && apt-get install python -y
    args:
      executable: /bin/bash
  
- name: basic
  hosts: all
  user: root
  vars_files:
  - variables/k8s-global.yml
  roles:
  - kubernetes/common
  - kubernetes/docker
  - kubernetes/ca
  - kubernetes/api-proxy

- name: etcd
  hosts: k8s_masters
  user: root
  vars_files:
  - variables/k8s-global.yml
  roles:
  - kubernetes/etcd

- name: k8s master
  hosts: k8s_masters
  user: root
  vars_files:
  - variables/k8s-global.yml
  roles:
  - kubernetes/masters-certs
  - kubernetes/control-plane
  - kubernetes/manifests

- name: k8s worker
  hosts: k8s_workers
  user: root
  vars_files:
  - variables/k8s-global.yml
  roles:
  - kubernetes/kubelet
