- name: prepare
  hosts: all
  user: root
  gather_facts: no
  roles:
  - kubernetes/prepare

- name: basic
  hosts: all
  user: root
  vars_files:
  - variables/k8s-global.yml
  roles:
  - kubernetes/common
  - kubernetes/firewall
  - kubernetes/docker
  - kubernetes/ca
  - kubernetes/api-proxy
  - kubernetes/etcd-certs

- name: k8s master
  hosts: k8s_masters
  user: root
  vars_files:
  - variables/k8s-global.yml
  roles:
  - kubernetes/etcd
  - kubernetes/masters-certs
  - kubernetes/control-plane
  - kubernetes/manifests

- name: k8s worker
  hosts: k8s_workers
  user: root
  vars_files:
  - variables/k8s-global.yml
  roles:
  - kubernetes/kubelet
