- name: make etcd directories
  file: dest={{ item }} state=directory recurse=yes
  with_items:
  - /etc/etcd
  - /var/lib/etcd
  
- name: create scripts to check cluster state/health and join new nodes
  template: src={{ item }}.j2 dest=/etc/etcd/{{ item }} mode=0755
  with_items:
  - node_join.sh
  - cluster_state.sh
  - cluster_health.sh
  
- name: get cluster state (new or existing)
  shell: /etc/etcd/cluster_state.sh
  register: etcd_cluster_state
  
- debug: msg="etcd cluster state is '{{ etcd_cluster_state.stdout }}'"
  run_once: true

- name: create systemd etcd.service unit
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service
  notify: restart_etcd
  
- name: join node to cluster and start etcd if required
  shell: /etc/etcd/node_join.sh
  when: etcd_cluster_state.stdout == "existing"

- name: restart etcd service if required
  meta: flush_handlers

- name: check that etcd cluster is up
  shell: /etc/etcd/cluster_health.sh
