- name: create calico RBAC manifest
  copy: src=calico-rbac.yaml dest=/etc/kubernetes/calico-rbac.yaml
  notify: apply_calico_rbac

- debug: msg='get etcd certs as base64 strings to inject this values into calico manifest'
  run_once: true

- shell: cat ca.pem | base64 --wrap=0
  args:
    chdir: /etc/kubernetes/ssl
  register: calico_etcd_ca
  delegate_to: "{{ groups.k8s_masters[0] }}"
  run_once: true

- shell: cat etcd.pem | base64 --wrap=0
  args:
    chdir: /etc/kubernetes/ssl
  register: calico_etcd_cert
  delegate_to: "{{ groups.k8s_masters[0] }}"
  run_once: true

- shell: cat etcd-key.pem | base64 --wrap=0
  args:
    chdir: /etc/kubernetes/ssl
  register: calico_etcd_key
  delegate_to: "{{ groups.k8s_masters[0] }}"
  run_once: true

- name: create calico deploy manifest
  template: src=calico-cni.yaml.j2 dest=/etc/kubernetes/calico-cni.yaml
  notify: apply_calico_deploy

# kube dns
- name: create kube-dns manifest
  template: src=kube-dns.yaml.j2 dest=/etc/kubernetes/kube-dns.yaml
  notify: apply_kubedns_deploy
