- name: get python package status
  raw: dpkg -l python
  args:
    executable: /bin/bash
  ignore_errors: yes
  register: python_pkg_stat

- name: install python
  raw: apt-get update -qq && apt-get install python -y
  args:
    executable: /bin/bash
  when: python_pkg_stat.rc != 0
