- name: restart_timesyncd
  systemd: name=systemd-timesyncd state=restarted enabled=yes
  when: ansible_distribution == "Ubuntu"

- name: restart_timedated
  systemd: name=systemd-timedated state=restarted enabled=yes
  when: ansible_distribution == "CentOS"

- name: restart_cron
  systemd: name=cron state=restarted

- name: restart_journald
  systemd: name=systemd-journald state=restarted

- name: sysctl_disable_ipv6
  shell: sysctl -p /etc/sysctl.d/99-disable-ipv6.conf
  args:
    executable: /bin/bash
