- name: restart_timesyncd
  systemd: name=systemd-timesyncd state=restarted

- name: restart_cron
  systemd: name=cron state=restarted

- name: restart_journald
  systemd: name=systemd-journald state=restarted

- name: sysctl_disable_ipv6
  shell: sysctl -p /etc/sysctl.d/99-disable-ipv6.conf
  args:
    executable: /bin/bash
