- name: get current etcd version
  shell: /etc/kubernetes/component-version.sh etcd
  register: current_etcd_v

- debug: msg="current_etcd_v={{ current_etcd_v.stdout }}"

- name: get etcd tarball
  get_url: 
    dest: /tmp/etcd-v{{ etcd_version }}.tar.gz
    url: https://storage.googleapis.com/etcd/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
    force: yes
  when: current_etcd_v.stdout != etcd_version

- name: unarchive etcd binaries
  unarchive: remote_src=yes src=/tmp/etcd-v{{ etcd_version }}.tar.gz dest=/tmp/
  when: current_etcd_v.stdout != etcd_version

- name: move etcd binaries to PATH
  copy: remote_src=yes mode=0755 src=/tmp/etcd-v{{ etcd_version }}-linux-amd64/{{ item }} dest=/usr/local/bin/{{ item }}
  with_items:
  - etcd
  - etcdctl
  when: current_etcd_v.stdout != etcd_version

- name: create systemd etcd-gateway.service unit
  template: src=etcd-gateway.service.j2 dest=/etc/systemd/system/etcd-gateway.service
  notify:
  - daemon_reload 
  - restart_etcd_gateway

- meta: flush_handlers

- name: ensure etcd-gateway is started
  systemd: name=etcd-gateway state=started
